# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Y530\Desktop\5X5.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TicTacToe(object):
    def setupUi(self, TicTacToe):
        TicTacToe.setObjectName("TicTacToe")
        TicTacToe.resize(566, 558)
        self.centralwidget = QtWidgets.QWidget(TicTacToe)
        self.centralwidget.setObjectName("centralwidget")
        self.b1 = QtWidgets.QToolButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(10, 10, 101, 91))
        self.b1.setText("")
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QToolButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(120, 10, 101, 91))
        self.b2.setText("")
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QToolButton(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(230, 10, 101, 91))
        self.b3.setText("")
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QToolButton(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(340, 10, 101, 91))
        self.b4.setText("")
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QToolButton(self.centralwidget)
        self.b5.setGeometry(QtCore.QRect(450, 10, 101, 91))
        self.b5.setText("")
        self.b5.setObjectName("b5")
        self.b10 = QtWidgets.QToolButton(self.centralwidget)
        self.b10.setGeometry(QtCore.QRect(450, 110, 101, 91))
        self.b10.setText("")
        self.b10.setObjectName("b10")
        self.b7 = QtWidgets.QToolButton(self.centralwidget)
        self.b7.setGeometry(QtCore.QRect(120, 110, 101, 91))
        self.b7.setText("")
        self.b7.setObjectName("b7")
        self.b8 = QtWidgets.QToolButton(self.centralwidget)
        self.b8.setGeometry(QtCore.QRect(230, 110, 101, 91))
        self.b8.setText("")
        self.b8.setObjectName("b8")
        self.b9 = QtWidgets.QToolButton(self.centralwidget)
        self.b9.setGeometry(QtCore.QRect(340, 110, 101, 91))
        self.b9.setText("")
        self.b9.setObjectName("b9")
        self.b6 = QtWidgets.QToolButton(self.centralwidget)
        self.b6.setGeometry(QtCore.QRect(10, 110, 101, 91))
        self.b6.setText("")
        self.b6.setObjectName("b6")
        self.b16 = QtWidgets.QToolButton(self.centralwidget)
        self.b16.setGeometry(QtCore.QRect(10, 310, 101, 91))
        self.b16.setText("")
        self.b16.setObjectName("b16")
        self.b12 = QtWidgets.QToolButton(self.centralwidget)
        self.b12.setGeometry(QtCore.QRect(120, 210, 101, 91))
        self.b12.setText("")
        self.b12.setObjectName("b12")
        self.b19 = QtWidgets.QToolButton(self.centralwidget)
        self.b19.setGeometry(QtCore.QRect(340, 310, 101, 91))
        self.b19.setText("")
        self.b19.setObjectName("b19")
        self.b20 = QtWidgets.QToolButton(self.centralwidget)
        self.b20.setGeometry(QtCore.QRect(450, 310, 101, 91))
        self.b20.setText("")
        self.b20.setObjectName("b20")
        self.b17 = QtWidgets.QToolButton(self.centralwidget)
        self.b17.setGeometry(QtCore.QRect(120, 310, 101, 91))
        self.b17.setText("")
        self.b17.setObjectName("b17")
        self.b13 = QtWidgets.QToolButton(self.centralwidget)
        self.b13.setGeometry(QtCore.QRect(230, 210, 101, 91))
        self.b13.setText("")
        self.b13.setObjectName("b13")
        self.b15 = QtWidgets.QToolButton(self.centralwidget)
        self.b15.setGeometry(QtCore.QRect(450, 210, 101, 91))
        self.b15.setText("")
        self.b15.setObjectName("b15")
        self.b18 = QtWidgets.QToolButton(self.centralwidget)
        self.b18.setGeometry(QtCore.QRect(230, 310, 101, 91))
        self.b18.setText("")
        self.b18.setObjectName("b18")
        self.b14 = QtWidgets.QToolButton(self.centralwidget)
        self.b14.setGeometry(QtCore.QRect(340, 210, 101, 91))
        self.b14.setText("")
        self.b14.setObjectName("b14")
        self.b11 = QtWidgets.QToolButton(self.centralwidget)
        self.b11.setGeometry(QtCore.QRect(10, 210, 101, 91))
        self.b11.setText("")
        self.b11.setObjectName("b11")
        self.b23 = QtWidgets.QToolButton(self.centralwidget)
        self.b23.setGeometry(QtCore.QRect(230, 410, 101, 91))
        self.b23.setText("")
        self.b23.setObjectName("b23")
        self.b21 = QtWidgets.QToolButton(self.centralwidget)
        self.b21.setGeometry(QtCore.QRect(10, 410, 101, 91))
        self.b21.setText("")
        self.b21.setObjectName("b21")
        self.b24 = QtWidgets.QToolButton(self.centralwidget)
        self.b24.setGeometry(QtCore.QRect(340, 410, 101, 91))
        self.b24.setText("")
        self.b24.setObjectName("b24")
        self.b25 = QtWidgets.QToolButton(self.centralwidget)
        self.b25.setGeometry(QtCore.QRect(450, 410, 101, 91))
        self.b25.setText("")
        self.b25.setObjectName("b25")
        self.b22 = QtWidgets.QToolButton(self.centralwidget)
        self.b22.setGeometry(QtCore.QRect(120, 410, 101, 91))
        self.b22.setText("")
        self.b22.setObjectName("b22")
        TicTacToe.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TicTacToe)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 566, 26))
        self.menubar.setObjectName("menubar")
        TicTacToe.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TicTacToe)
        self.statusbar.setObjectName("statusbar")
        TicTacToe.setStatusBar(self.statusbar)

        self.retranslateUi(TicTacToe)
        QtCore.QMetaObject.connectSlotsByName(TicTacToe)

    def retranslateUi(self, TicTacToe):
        _translate = QtCore.QCoreApplication.translate
        TicTacToe.setWindowTitle(_translate("TicTacToe", "TicTacToe"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TicTacToe = QtWidgets.QMainWindow()
    ui = Ui_TicTacToe()
    ui.setupUi(TicTacToe)
    TicTacToe.show()
    sys.exit(app.exec_())
